# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.label.setObjectName("label")
        self.le1 = QtWidgets.QLineEdit(Form)
        self.le1.setGeometry(QtCore.QRect(110, 10, 281, 21))
        self.le1.setObjectName("le1")
        self.btn_add = QtWidgets.QPushButton(Form)
        self.btn_add.setGeometry(QtCore.QRect(10, 270, 181, 23))
        self.btn_add.setObjectName("btn_add")
        self.btn_edit = QtWidgets.QPushButton(Form)
        self.btn_edit.setGeometry(QtCore.QRect(204, 270, 191, 23))
        self.btn_edit.setObjectName("btn_edit")
        self.le2 = QtWidgets.QLineEdit(Form)
        self.le2.setGeometry(QtCore.QRect(110, 40, 281, 21))
        self.le2.setObjectName("le2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.label_2.setObjectName("label_2")
        self.le3 = QtWidgets.QLineEdit(Form)
        self.le3.setGeometry(QtCore.QRect(110, 70, 281, 21))
        self.le3.setObjectName("le3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 91, 21))
        self.label_3.setObjectName("label_3")
        self.le4 = QtWidgets.QLineEdit(Form)
        self.le4.setGeometry(QtCore.QRect(110, 100, 281, 21))
        self.le4.setObjectName("le4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 91, 21))
        self.label_4.setObjectName("label_4")
        self.le5 = QtWidgets.QLineEdit(Form)
        self.le5.setGeometry(QtCore.QRect(110, 130, 281, 21))
        self.le5.setObjectName("le5")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 91, 21))
        self.label_5.setObjectName("label_5")
        self.le6 = QtWidgets.QLineEdit(Form)
        self.le6.setGeometry(QtCore.QRect(110, 160, 281, 21))
        self.le6.setObjectName("le6")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 91, 21))
        self.label_6.setObjectName("label_6")
        self.btn_clear = QtWidgets.QPushButton(Form)
        self.btn_clear.setGeometry(QtCore.QRect(320, 200, 75, 23))
        self.btn_clear.setObjectName("btn_clear")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "название сорта"))
        self.btn_add.setText(_translate("Form", "Добавить"))
        self.btn_edit.setText(_translate("Form", "Изменить"))
        self.label_2.setText(_translate("Form", "степень обжарки"))
        self.label_3.setText(_translate("Form", "молотый/в зернах"))
        self.label_4.setText(_translate("Form", "описание вкуса"))
        self.label_5.setText(_translate("Form", "цена"))
        self.label_6.setText(_translate("Form", "объем упаковки"))
        self.btn_clear.setText(_translate("Form", "Очистить"))
